### ISSUE TITLE
Edit tour does not display the changes on the /music page after clicking the Edit Tour button (I had to manually reload the page for it to update), please fix

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#511]
```JSOG.js:42 Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at s (https://web-jam.com/app.877eff1206001bf1baad.bundle.js:320:25357)
    at t (https://web-jam.com/app.877eff1206001bf1baad.bundle.js:320:25563)
    at s (https://web-jam.com/app.877eff1206001bf1baad.bundle.js:320:25389)
    at t (https://web-jam.com/app.877eff1206001bf1baad.bundle.js:320:25563)
    at s (https://web-jam.com/app.877eff1206001bf1baad.bundle.js:320:25389)
    at t (https://web-jam.com/app.877eff1206001bf1baad.bundle.js:320:25563)
    at s (https://web-jam.com/app.877eff1206001bf1baad.bundle.js:320:25389)
    at t (https://web-jam.com/app.877eff1206001bf1baad.bundle.js:320:25563)
    at s (https://web-jam.com/app.877eff1206001bf1baad.bundle.js:320:25389)
    at t (https://web-jam.com/app.877eff1206001bf1baad.bundle.js:320:25563)
s @ JSOG.js:42
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
(anonymous) @ JSOG.js:56
o @ JSOG.js:51
t @ JSOG.js:66
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
(anonymous) @ JSOG.js:56
o @ JSOG.js:51
t @ JSOG.js:66
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
(anonymous) @ JSOG.js:56
o @ JSOG.js:51
t @ JSOG.js:66
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
s @ JSOG.js:44
t @ JSOG.js:68
(anonymous) @ JSOG.js:56
o @ JSOG.js:51
t @ JSOG.js:66
s @ JSOG.js:44
t @ JSOG.js:68
n.encode @ JSOG.js:70
(anonymous) @ jsonTransform.ts:7
in @ createTransform.js:16
(anonymous) @ createPersistoid.js:66
h @ createPersistoid.js:65
setInterval (async)
update @ createPersistoid.js:51
l @ persistReducer.js:41
(anonymous) @ persistReducer.js:149
v @ redux.js:213
(anonymous) @ index.js:11
editTour @ index.tsx:93
onClick @ index.tsx:106
s @ react-dom.production.min.js:14
p @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
b @ react-dom.production.min.js:15
ot @ react-dom.production.min.js:52
rt @ react-dom.production.min.js:51
st @ react-dom.production.min.js:52
pt @ react-dom.production.min.js:56
N @ react-dom.production.min.js:287
I @ react-dom.production.min.js:19
Xt @ react-dom.production.min.js:70
$t @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
Yr @ react-dom.production.min.js:122
z @ react-dom.production.min.js:287
qt @ react-dom.production.min.js:68
Show 109 more frames
21index.js:36 Uncaught TypeError: r[e].write is not a function
    at e.exports._write (index.js:36)
    at e.exports.write (index.js:41)
    at e.exports.write (index.js:10)
    at w.r.emit (index.js:8)
    at u.onEvent [as _onEventHandler] (clientsocket.js:376)
    at u._onMessage (transport.js:286)
    at WebSocket.s.onmessage (transport.js:82)
_write @ index.js:36
write @ index.js:41
write @ index.js:10
r.emit @ index.js:8
onEvent @ clientsocket.js:376
u._onMessage @ transport.js:286
s.onmessage @ transport.js:82
transport.js:230 Uncaught TypeError: Cannot read property 'call' of undefined
    at transport.js:230
    at Array.forEach (<anonymous>)
    at u._abortAllPendingEventsDueToBadConnection (transport.js:217)
    at u._destroy (transport.js:249)
    at transport.js:316
```

**Comment by Unesdala** [comment]
@JoshuaVSherman Can you provide more details on this?

It seems to be working as intended on my end, testing locally.

**Comment by JoshuaVSherman** [comment]
@Unesdala not sure how else to explain, click `Edit` on one of the tour events, change something in the form (for example the location or something), click Edit button, it redirects to the /music page, but that tour does not change in the Table, it still shows the older information, but if you reload the page, then it is updated (obviously it gets updated in the database, but it is not updating in the Redux store which is cached to SessionStorage)

**Comment by JoshuaVSherman** [comment]
@Unesdala this is still not fixed on production, so I'll work on it

**Comment by JoshuaVSherman** [comment]
https://stackoverflow.com/questions/57906696/redux-persist-createpersistoid-error-serializing-state-typeerror-converting-ci

**Comment by JoshuaVSherman** [comment]
https://www.npmjs.com/package/flatted

**Comment by JoshuaVSherman** [comment]
our other option is to just not persist the circular json (I think it was the socket cluster client)
https://blog.reactnativecoach.com/the-definitive-guide-to-redux-persist-84738167975
