### ISSUE TITLE
Write jest unit tests to fully cover MusicPlayer and Originals code, use correct form and expect statements

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#75]
* [ ] src/components/MusicPlayer/index.js
* [x] src/containers/Originals/index.js

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves please finish this up
src/components/MusicPlayer |    91.36 |    72.22 |       80 |    91.25 |                   |
  index.js                  |    91.36 |    72.22 

also, please fix these error/warnings:

  console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Not implemented: HTMLMediaElement.prototype.play
        at module.exports (/home/webjamllc/GitHub/JaMmusic/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
        at HTMLAudioElementImpl.play (/home/webjamllc/GitHub/JaMmusic/node_modules/jsdom/lib/jsdom/living/nodes/HTMLMediaElement-impl.js:120:5)
        at HTMLAudioElement.play (/home/webjamllc/GitHub/JaMmusic/node_modules/jsdom/lib/jsdom/living/generated/HTMLMediaElement.js:60:45)
        at FilePlayer.play (/home/webjamllc/GitHub/JaMmusic/node_modules/react-player/lib/players/FilePlayer.js:272:33)
        at Player.componentWillReceiveProps (/home/webjamllc/GitHub/JaMmusic/node_modules/react-player/lib/Player.js:203:21)
        at callComponentWillReceiveProps (/home/webjamllc/GitHub/JaMmusic/node_modules/react-dom/cjs/react-dom.development.js:11441:14)
        at updateClassInstance (/home/webjamllc/GitHub/JaMmusic/node_modules/react-dom/cjs/react-dom.development.js:11651:7)
        at updateClassComponent (/home/webjamllc/GitHub/JaMmusic/node_modules/react-dom/cjs/react-dom.development.js:14694:20)
        at beginWork (/home/webjamllc/GitHub/JaMmusic/node_modules/react-dom/cjs/react-dom.development.js:15644:16)
        at performUnitOfWork (/home/webjamllc/GitHub/JaMmusic/node_modules/react-dom/cjs/react-dom.development.js:19312:12) undefined

  console.warn node_modules/react-player/lib/Player.js:193
    ReactPlayer: the attempt to load https://dl.dropboxusercontent.com/s/ceqa0bk1swccgs2/Don%27t%20Go.mp3?dl=0 is being deferred until the player has loaded

  console.warn node_modules/react-player/lib/Player.js:193
    ReactPlayer: the attempt to load https://dl.dropboxusercontent.com/s/3tisiordjrgjkoq/Good%20Enough.mp3?dl=0 is being deferred until the player has loaded
